version: '3'
services:

  # Mongodb - Database
  mongo:
    image: mongo:latest
    ports:
      - "27018:27017"
    volumes:
      - mongo-data-volume:/data/db

  # RabbitMQ - Message queues
  rabbit:
     image: rabbitmq:management
     hostname: rabbit
     volumes:
        - rabbit-volume:/etc/rabbitmq
     ports:
        - "4000:5672"
        - "4001:15672"
     healthcheck: 
        test: ["CMD", "curl", "-f", "http://rabbit:15672"]
        interval: 30s
        timeout: 10s
        retries: 5

  # Minio - Object storage
  minio:
    image: minio/minio
    volumes:
      - minio-data:/data/minio
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server /data/minio

  # Videos microservice
  video-service:
    build: ../blue-stream-video
    env_file:
      - ./env/node.env
      - ./env/mongo.env
      - ./env/rabbitmq.env
    restart: always
    depends_on:
      - mongo
      - rabbit
    links:
      - mongo
      - rabbit

  # Transcoder Service
  transcoder-service:
    build: ../blue-stream-transcoder
    env_file: 
      - ./env/rabbitmq.env
      - ./env/s3.env
    restart: always
    depends_on:
      - rabbit
    links:
      - rabbit

  # Uploader Service
  uploader-service:
    build: ../blue-stream-uploader
    ports:
      - "5002:3000"
    env_file:
      - ./env/node.env
      - ./env/rabbitmq.env
      - ./env/s3.env
    environment:
      MAX_FILE_SIZE: 20971520000
    restart: always
    depends_on:
      - rabbit
    links:
      - rabbit

  # Comment Service
  comment-service:
    build: ../blue-stream-comments
    env_file:
      - ./env/node.env
      - ./env/rabbitmq.env
      - ./env/mongo.env
    restart: always
    depends_on:
      - rabbit
      - mongo
    links:
      - rabbit
      - mongo

  # Reaction Service
  reaction-service:
    build: ../blue-stream-reactions
    env_file:
      - ./env/node.env
      - ./env/rabbitmq.env
      - ./env/mongo.env
    restart: always
    depends_on:
      - rabbit
      - mongo
    links:
      - rabbit
      - mongo

  # Channel Service
  channel-service:
    build: ../blue-stream-channel
    env_file:
      - ./env/node.env
      - ./env/rabbitmq.env
      - ./env/mongo.env
    restart: always
    depends_on:
      - rabbit
      - mongo
    links:
      - rabbit
      - mongo  

  # User Service
  user-service:
    build: ../blue-stream-users
    env_file:
      - ./env/node.env
      - ./env/mongo.env
      - ./env/rabbitmq.env
    restart: always
    depends_on:
      - rabbit
      - mongo
    links:
      - rabbit
      - mongo

  # Streamer Service
  streamer-service:
    build: ../blue-stream-streamer
    ports:
      - "5005:3000"
    env_file:
      - ./env/node.env
      - ./env/rabbitmq.env
      - ./env/s3.env
    restart: always
    depends_on:
      - rabbit
      - minio
    links:
      - rabbit
      - minio

  # Video Compositor Service
  video-compositor-service:
    build: ../blue-stream-video-compositor
    ports:
      - "7001:3000"
    env_file:
      - ./env/node.env
      - ./env/rabbitmq.env
      - ./env/compositor.env
    restart: always
    depends_on:
      - rabbit
      - user-service
      - video-service
      - channel-service
    links:
      - rabbit
      - user-service
      - video-service
      - channel-service

  # Comment Compositor Service
  comment-compositor-service:
    build: ../blue-stream-comment-compositor
    ports:
      - "7002:3000"
    env_file:
      - ./env/node.env
      - ./env/rabbitmq.env
      - ./env/compositor.env
    restart: always
    depends_on:
      - rabbit
      - user-service
      - comment-service
      - reaction-service
    links:
      - rabbit
      - user-service
      - comment-service
      - reaction-service

  # Reaction Compositor Service
  reaction-compositor-service:
    build: ../blue-stream-reaction-compositor
    ports:
      - "7003:3000"
    env_file:
      - ./env/node.env
      - ./env/rabbitmq.env
      - ./env/compositor.env
    restart: always
    depends_on:
      - rabbit
      - comment-service
      - video-service
      - reaction-service
    links:
      - rabbit
      - comment-service
      - video-service
      - reaction-service

  # Client
  angular-client:
    build: ../blue-stream-client
    ports:
      - "80:80"
    restart: always
    depends_on:
      - streamer-service
      - uploader-service
      - transcoder-service
      - video-compositor-service
      - comment-compositor-service
      - reaction-compositor-service


volumes:
  mongo-data-volume:
  rabbit-volume:
  minio-data: